require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      user: {
        email_address: "test@example.com",
        password: "password",
        password_confirmation: "password",
        name: "Test User",
        role: "librarian"
      }
    }
  }

  let(:invalid_attributes) {
    {
      user: {
        email_address: "",
        password: "",
        password_confirmation: "",
        name: "",
        role: ""
      }
    }
  }

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User" do
        expect {
          post users_url, params: valid_attributes, as: :json
        }.to change(User, :count).by(1)
      end

      it "renders a JSON response with the new user" do
        post users_url, params: valid_attributes, as: :json

        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
        expect(json_response).to eql({ "id" => User.last.id, "email_address" => "test@example.com", "name" => "Test User", "role" => "librarian" })
      end
    end

    context "with invalid parameters" do
      it "does not create a new User" do
        expect {
          post users_url, params: invalid_attributes, as: :json
        }.to change(User, :count).by(0)
      end

      it "renders a JSON response with errors for the new user" do
        post users_url, params: invalid_attributes, as: :json

        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
        expect(json_response).to eql({ "email_address" => [ "can't be blank", "is invalid" ], "password" => [ "can't be blank" ], "name" => [ "can't be blank" ], "role" => [ "can't be blank" ] })
      end
    end
  end
end
