default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres


development:
  <<: *default
  database: libray_management_development

test:
  <<: *default
  database: libray_management_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: libray_management_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: libray_management_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: libray_management_production_cable
    migrations_paths: db/cable_migrate
